version: "3.8"
services:
  db2:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3309:3306"
    # network_mode: "host"
    volumes:
      - ./init/db/my.cnf:/etc/mysql/conf.d/my.cnf
